name: Erlang CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ['22.3', '23.3', '24.0']

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: '3.16.1'
    - name: Compile
      run: rebar3 compile
    - name: Format check
      run: rebar3 format --verify
    - name: Run tests and verifications
      run: rebar3 test || DEBUG=1 DIAGNOSTIC=1 rebar3 test # first dialyzer run always complains and 'test' alias runs dialyzer
